level_0 = {'title':"No Level Achieved",
           'description':
"""You may have a solid idea, \
but this has not yet been translated into applied research and development on the technology's basic principles. \
Update your project's progress as it evolves, to calculate its readiness level."""}

level_1 = {
	'title': "Basic Principles Observed",
    'description':
"""This is the lowest level of technology readiness, \
but research begins to be translated into applied research and development. \
Examples might include paper studies of the technology's basic properties.""",
	'requirements': [
	{'description': "'Back of envelope' environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Physical laws and assumptions used in new technologies defined",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Have some concept in mind that may be realizable in software",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Know what software needs to do in general terms",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Paper studies confirm basic principles",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Mathematical formulations of concepts that might be realizable in software",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Have an idea that captures the basic principles of a possible algorithm",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Initial scientific observations reported in journals/conference proceedings/technical reports",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Basic scientific principles observed",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Know who cares about category, e.g., sponsor, money source",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Research hypothesis formulated",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Know who will perform research and where it will be done",
	 'category': "prl",
	 'technology': "both"},
	]
}

level_2 = {
	'title': "Technology Concept Formulated",
    'description':
"""Invention begins. \
After the basic principles have been observed in TRL1, the practical applications can now be invented. \
Applications are speculative and there may be no proof or detailed analysis to support the assumptions. \
Examples are limited to analytic studies.""",
	'requirements': [
	{'description': "Customer Identified",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Potential system or component application(s) have been identified",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Paper studies show that application is feasible",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Know what program the technology will support",
	 'category': "prl",
	 'technology': "both"},
	{'description': "An apparent theoretical or empirical design solution identified",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Basic elements of technology have been identified",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Desktop environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Components of technology have been partially characterized",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Performance predictions made for each element",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Customer expresses interest in application",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Some coding to confirm basic principles",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Initial analysis shows what major functions need to be done",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Modeling & Simulation only used to verify physical principles",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "System architecture defined in terms of major functions to be performed",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Experiments performed with synthetic data",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Requirement tracking system defined to manage requirements creep",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Rigorous analytical studies confirm basic principles",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Analytical studies reported in scientific journals/conference proceedings/technical reports",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Individual parts of the technology work (No real attempt at integration)",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Know what hardware software will be hosted on",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Know what output devices are available",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Investment Strategy Sheet",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Know capabilities and limitations of researchers and research facilities",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Know what experiments you need to do (research approach)",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Qualitative idea of risk areas (cost, schedule, performance)",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Have rough idea of how to market technology (Who's interested, how will they find out about it?)",
	 'category': "prl",
	 'technology': "both"},
	]
}

level_3 = {
	'title': "Experimental Proof of Concept",
    'description':
"""Active research and development is initiated. \
This includes analytical studies and laboratory studies to physically validate analytical predictions of separate elements of the technology. \
Examples include components that are not yet integrated or representative.""",
	'requirements': [
	{'description': "Academic environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Predictions of elements of technology capability validated by Analytical Studies",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Analytical studies verify predictions, produce algorithms",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Science known to extent that mathematical and/or computer models and simulations are possible",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Preliminary system performance characteristics and measures have been identified and estimated",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Outline of software algorithms available",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Predictions of elements of technology capability validated by Modeling and Simulation",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Preliminary coding verifies that software can satisfy an operational need",
	 'category': "trl",
	 'technology': "software"},
	{'description': "No system components, just basic laboratory research equipment to verify physical principles",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Laboratory experiments verify feasibility of application",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Predictions of elements of technology capability validated by Laboratory Experiments",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Customer representative identified to work with development team",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Customer participates in requirements generation",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Cross technology effects (if any) have begun to be identified",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Design techniques have been identified/developed",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Paper studies indicate that system components ought to work together",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Customer identifies transition window(s) of opportunity",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Metrics established",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Scaling studies have been started",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Experiments carried out with small representative data sets",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Algorithms run on surrogate processor in a laboratory environment",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Current manufacturability concepts assessed",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Know what software is presently available that does similar task (100% = Inventory completed)",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Existing software examined for possible reuse",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Producibility needs for key breadboard components identified",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Know limitations of presently available software (Analysis of current software completed)",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Scientific feasibility fully demonstrated",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Analysis of present state of the art shows that technology fills a need",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Risk areas identified in general terms",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Risk mitigation strategies identified",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Rudimentary best value analysis performed, not including cost factors",
	 'category': "prl",
	 'technology': "both"},
	]
}

level_4 = {
	'title': "Technology Validated in Lab",
    'description':
"""The basic technological components are integrated to establish that they will work together. \
This is relatively "low fidelity" compared to the eventual system. \
Examples include integration of "ad hoc" hardware in the laboratory.""",
	'requirements': [
	{'description': "Cross technology issues (if any) have been fully identified",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Ad hoc and available laboratory components are surrogates for system components",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Individual components tested in laboratory/by supplier (contractor's component acceptance testing)",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Piece parts and components in a pre-production form exist",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "M&S used to simulate some components and interfaces between components",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Formal system architecture development begins",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Customer publishes requirements document",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Overall system requirements for end user's application are known",
	 'category': "trl",
	 'technology': "both"},
	{'description': "System performance metrics have been established",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Analysis provides detailed knowledge of specific functions software needs to perform",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Laboratory requirements derived from system requirements are established",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Available components assembled into system breadboard",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Laboratory experiments with available components show that they work together (lab kludge)",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Requirements for each function established",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Algorithms converted to pseudocode",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Analysis of data requirements and formats completed",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Stand-alone modules follow preliminary system architecture plan",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Hardware in the loop/computer in the loop tools to establish component compatibility",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Designs verified through formal inspection process",
	 'category': "mrl",
	 'technology': "software"},
	{'description': "S&T exit criteria established",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Technology demonstrates basic functionality in simplified environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Able to estimate software program size in lines of code and/or function points",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Scalable technology prototypes have been produced",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Draft conceptual designs have been documented",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Design techniques identified/defined to where small applications may be analyzed/simulated",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Controlled laboratory environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Initial cost drivers identified",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Experiments with full scale problems and representative data sets",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Integration studies have been started",
	 'category': "mrl",
	 'technology': "both"},
	{'description': "CAIV targets set",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Individual functions or modules demonstrated in a laboratory environment",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Key manufacturing processes identified",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Scaling documents and diagrams of technology have been completed",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Some ad hoc integration of functions or modules demonstrates that they will work together",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Key manufacturing processes assessed in laboratory",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Draft Systems Engineering Master Plan (SEMP)",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Low fidelity technology “system” integration and engineering completed in a lab environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Mitigation strategies identified to address manufacturability / producibility shortfalls",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Customer commits to transition through ATD commissioning and/or MOU",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Functional work breakdown structure developed",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Integrated Product Team (IPT) formally established with charter",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Customer representative is member of IPT",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Formal risk management program initiated",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Preliminary Failure Mode and Effects Analysis (FMEA) or Risk Waterfall analysis performed",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Technology availability dates established",
	 'category': "prl",
	 'technology': "both"},
	]
}

level_5 = {
	'title': "Technology Validated in Relevant Environment",
    'description':
"""The fidelity of the breadboard technology increases significantly. \
The basic technological components are integrated with reasonably realistic supporting elements so it can be tested in a simulated environment. \
Examples include "high fidelity" laboratory integration of components.""",
	'requirements': [
	{'description': "Cross technology effects (if any) identified and established through analysis",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Pre-production hardware available",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "System interface requirements known",
	 'category': "trl",
	 'technology': "both"},
	{'description': "System requirements flow down through work breakdown structure (systems engineering begins)",
	 'category': "prl",
	 'technology': "both"},
	{'description': "System software architecture established",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Targets for improved yield established",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "External interfaces described as to source, format, structure, content, and method of support",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Analysis of internal interface requirements completed",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Trade studies and lab experiments define key manufacturing processes",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Interfaces between components/subsystems are realistic (Breadboard with realistic interfaces)",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Significant engineering and design changes",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Coding of individual functions/modules completed",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Prototypes have been created",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Tooling and machines demonstrated in lab",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "High fidelity lab integration of system completed, ready for test in realistic/simulated environments",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Design techniques have been defined to the point where largest problems defined",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Form, fit, and function for application addressed in conjunction with end user development staff",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Fidelity of system mock-up improves from breadboard to brassboard",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Quality and reliability considered, but target levels not yet established",
	 'category': "mrl",
	 'technology': "both"},
	{'description': "Some special purpose components combined with available laboratory components",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Three view drawings and wiring diagrams have been submitted",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Laboratory environment modified to approximate operational environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Initial assesment of assembly needs performed",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Detailed design drawings have been completed",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Sigma levels needed to satisfy CAIV targets defined",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Draft SEMP addresses integration",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Draft SEMP addresses test and evaluation",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Draft SEMP addresses mechanical and electrical interfaces",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Production processes have been reviewed with Manufacturing and Producibility office(s)",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Draft SEMP addresses performance; translate measured to expected final performance",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Risk management plan documented",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Functions integrated into modules",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Configuration management plan in place",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Individual functions tested to verify that they work",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Individual modules and functions tested for bugs",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Integration of modules/functions demonstrated in a laboratory environment",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Formal inspection of all modules/components completed as part of configuration management",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Configuration management plan documented",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Draft Test & Evaluation Master Plan (TEMP)",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Algorithms run on processor with characteristics representative of target environment",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Preliminary hardware technology “system” engineering report (Draft SEMP) completed",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Customer commits to transition via POM process",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Draft Transition Plan with Business Case",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Failure Mode and Effects Analysis (FMEA) performed",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Value analysis includes analysis of multiple technology and non-material alternatives",
	 'category': "prl",
	 'technology': "both"},
	{'description': "IPT develops requirements matrix with thresholds and objectives",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Physical work breakdown structure available",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Value analysis includes life-cycle cost analysis",
	 'category': "prl",
	 'technology': "both"},
	]
}					

level_6 = {
	'title': "Technology Demonstrated in Relevant Environment",
    'description':
"""A representative model or prototype system, which is well beyond that of TRL5, is tested in a relevant environment. \
This represents a major step up in the technology's demonstrated readiness. \
Examples include testing a prototype in a high fidelity laboratory environment or in simulated operational environment.""",
	'requirements': [
	{'description': "Cross technology issue measurement and performance characteristic validations completed",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Quality and reliability levels established",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Frequent design changes occur",
	 'category': "mrl",
	 'technology': "both"},
	{'description': "Draft design drawings are nearly complete",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Operating environment for eventual system known",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Collection of actual maintainability, reliability, and supportability data has been started",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Design to cost goals identified",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Investment needs for process and tooling determined",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "M&S used to simulate system performance in an operational environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Final Test & Evaluation Master Plan (TEMP)",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Factory acceptance testing of laboratory system in laboratory setting",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Representative model / prototype tested in high-fidelity lab / simulated operational environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Realistic environment outside the lab, but not the eventual operating environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Final Systems Engineering Master Plan (SEMP)",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Inventory of external interfaces completed",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Technology Transition Agreement has been updated",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Scaling issues that remain are identified and supporting analysis is complete",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Analysis of timing constraints completed",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Analysis of database structures and interfaces completed",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Have begun to establish an interface control process",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Draft production planning has been reviewed by end user and developer",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Critical manufacturing processes prototyped",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Most pre-production hardware is available",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Technology Transition Agreement has been coordinated and approved by end user",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Prototype implementation includes functionality to handle large scale realistic problems",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Algorithms parially integrated with existing hardware / software systems",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Materials, process, design, and integration methods have been employed",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Individual modules tested to verify that the module components (functions) work together",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Technology ”system” specification complete",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Components are functionally compatible with operational system",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Representative software system or prototype demonstrated in a laboratory environment",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Laboratory system is high-fidelity functional prototype of operational system",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Formal configuration management program defined to control change process",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Integration demonstrations have been completed",
	 'category': "mrl",
	 'technology': "both"},
	{'description': "Final Technical Report",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Production issues have been identified and major ones have been resolved",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Limited software documentation available",
	 'category': "trl",
	 'technology': "software"},
	{'description': "Verification, Validation and Accreditation (VV&A) initiated",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Process and tooling are mature",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Production demonstrations are complete",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "'Alpha' version software has been released",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Engineering feasibility fully demonstrated",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Final Transition Plan with Business Case",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Acquisition program milestones established",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Value analysis includes business case",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Technical alternatives include 'do nothing case'",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Formal requirements document available",
	 'category': "prl",
	 'technology': "both"},
	]
}

level_7 = {
	'title': "System Prototype Demonstration in Operational Environment",
    'description':
"""The prototype is near or at the planned operational system. \
This represents a major step up from TRL6, requiring the demonstration of an actual system prototype in an operational environment, such as in aircraft, vehicle, or space. \
Examples include testing the prototype in a test bed aircraft.""",
	'requirements': [
	{'description': "Materials, processes, methods, and design techniques have been identified",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Materials and manufacturing process and procedures initially demonstrated",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "M&S used to simulate some unavailable elements of system, but these instances are rare",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Prototype system built on 'soft' tooling",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Each system/software interface tested individually under stressed and anomolous conditions",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Algorithms run on processor(s) in operating environment",
	 'category': "trl",
	 'technology': "software"},
	{'description': "VV&A in process with the verification step that software specifications are met completed",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Process tooling and inspection / test equipment demonstrated in production environment",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Machines and tooling proven",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Design changes decrease significantly",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Operational environment, but not the eventual platform, e.g., test-bed aircraft",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Maintainability, reliability, and supportability data is above 60% of total needed data",
	 'category': "mrl",
	 'technology': "both"},
	{'description': "Draft design drawings are complete",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Materials, processes, methods, and design techniques are moderately developed and verified",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Scaling is complete",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Pre-production hardware is available; quantities may be limited",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Components are representative of production components",
	 'category': "trl",
	 'technology': "hardware"},
	{'description': "Design to cost goals validated",
	 'category': "prl",
	 'technology': "hardware"},
	{'description': "Initial sigma levels established",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Manufacturing processes generally well understood",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Most software bugs removed",
	 'category': "mrl",
	 'technology': "software"},
	{'description': "Production planning is complete",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Most functionality available for demonstration in simulated operational environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Operational/flight testing of laboratory system in representational environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Prototype improves to pre-production quality",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "'Beta' version software has been released",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Fully integrated prototype demonstrated in actual or simulated operational environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "System prototype successfully tested in a field environment",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Ready for Low Rate Initial Production (LRIP)",
	 'category': "mrl",
	 'technology': "hardware"},
	]
}

level_8 = {
	'title': "System Complete and Qualified",
    'description':
"""The technology is proven to work in its final form and under expected conditions. \
In most cases, this TRL represents the end of true system development. \
Examples include developmental test and evaluation of the system in its intended weapon system to determine if it meets specifications.""",
	'requirements': [
	{'description': "Components are form, fit, and function compatible with operational system",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Cost estimates <125% cost goals (e.g., design to cost goals met for LRIP)",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "System is form, fit, and function design for intended application and weapon system platform",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Form, fit, and function demonstrated in eventual platform/weapon system",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Machines and tooling demonstrated in production environment",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Interface control process has been completed",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Most software user documentation completed and under configuration control",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Most training documentation completed and under configuration control",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Most maintenance documentation completed and under configuration control",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Final architecture diagrams have been submitted",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Manufacturing processes demonstrated by pilot line, LRIP, or similar item production",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Manufacturing processes demonstrate acceptable yield and producibility levels",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Software thoroughly debugged",
	 'category': "trl",
	 'technology': "software"},
	{'description': "All functionality demonstrated in simulated operational environmenet",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Manufacturing process controlled to 4-sigma or appropriate quality level",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "All materials are in production and readily available",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "System qualified through test and evaluation on actual platform (DT&E completed)",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Maintainability, reliability, and supportability data collection has been completed",
	 'category': "mrl",
	 'technology': "both"},
	{'description': "VV&A validation step completed, software works in real world",
	 'category': "prl",
	 'technology': "software"},
	{'description': "DT&E completed, system meets specifications",
	 'category': "trl",
	 'technology': "both"},
	{'description': "VV&A accreditation step completed, software authorized for use in intended weapon system",
	 'category': "prl",
	 'technology': "software"},
	{'description': "Ready for Full Rate Production",
	 'category': "mrl",
	 'technology': "hardware"},
	]
}

level_9 = {
	'title': "Actual System Proven in Operational Environment",
    'description':
"""The actual application of the technology in its final form and under mission conditions, \
such as those encountered in operational test and evaluation. \
Examples include using the system under operational mission conditions.""",
	'requirements': [
	{'description': "Operational Concept has been implemented successfully",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Cost estimates <110% cost goals or meet cost goals (e.g., design to cost goals met)",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Affordability issues built into initial production and evolutionary acquisition milestones",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Design stable, few or no design changes",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "System has been installed and deployed in intended weapon system platform",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Safety/Adverse effects issues have been identified and mitigated",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Actual system fully demonstrated",
	 'category': "trl",
	 'technology': "both"},
	{'description': "Training Plan has been implemented",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Supportability Plan has been implemented",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Program Protection Plan has been implemented",
	 'category': "prl",
	 'technology': "both"},
	{'description': "Actual mission system 'flight proven' through successful mission operations (OT&E completed)",
	 'category': "trl",
	 'technology': "both"},
	{'description': "All manufacturing processes controlled to 6-sigma  or appropriate quality level",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "Stable production",
	 'category': "mrl",
	 'technology': "hardware"},
	{'description': "All documentation completed",
	 'category': "prl",
	 'technology': "both"},
	]
}

LEVELS = [level_0, level_1, level_2, level_3, level_4, level_5, level_6, level_7, level_8, level_9]

def get_level(number):
	return LEVELS[number]
